#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9 0 

bspc config border_width         4
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#ff0048
#bspc config focused_border_color \#64d86b
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

picom & 
$HOME/.config/polybar/launch.sh --cuts & 
#feh --bg-scale $HOME/pictures/wallpapers/matrix.jpg &
feh --bg-scale $HOME/pictures/wallpapers/cyberpunk-city.jpg &
nextcloud &
discord &
xsetroot -cursor_name left_ptr &
playerctld daemon
