#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         4
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#d81c2b
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

#autostart
feh --bg-scale ~/pictures/wallpapers/cyberpunk-girl.jpg &
$HOME/.config/polybar/launch.sh --cuts &
picom -b --experimental-backends &
nextcloud &
xsetroot -cursor_name left_ptr & 
setxkbmap -option caps:escape,shift:both_capslock &
