#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DP-2 -d 1 2 3 4 5 
bspc monitor HDMI-0 -d 6 7 8 9 0 

bspc config border_width         4
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focused_border_color \#ff0088
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

$HOME/.config/polybar/launch.sh --cuts & 
picom -b --experimental-backends & 
feh --bg-scale $HOME/pictures/wallpapers/neon-circle.jpg &
nextcloud &
xsetroot -cursor_name left_ptr &
setxkbmap -option caps:swapescape &
playerctld daemon
